<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Winfertility Tests - Android</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2b6cb1b8-3718-4e84-b8bf-62349049190e</testSuiteGuid>
   <testCaseLink>
      <guid>e5938fdf-e45f-4f6e-8582-5bfc1e9f4b16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should able to login successfully with valid email and password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcf3fdb0-0b72-4324-8970-36afed531a18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d5bf77a-b203-4939-96fd-c89ec72fed92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>641d96dc-c9c4-4890-b65a-08191f34062a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should able to logout from application</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c88a5a3-5dc5-4a49-ae2a-c59baeae9948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b82907c-dd94-4eac-9ff0-5d2ba92adc06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f539cca-7514-4aaf-9f82-95bf0fe1f4e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should able to navigate to Forgot password screen using Forgot Password link and vice versa</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8e2a2a18-8197-454c-a216-d814eab64a55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should able to navigate to sign up screen using Create New Account link</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6288658c-207f-418d-b87e-36dab08defd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should receive error message for account locked after 3 unsuccessfull attempts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>760e25ba-e8b3-4ef6-b6a7-159089e494eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4fb42a4-1266-4806-9df5-c28b9226695d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7095f0d-2b71-406e-ad2c-62de3db7c490</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should receive error message for invalid email address</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>444ab84f-520a-4527-8f1e-fd72a1a55213</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should receive error message for invalid password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b21f906a-b0d2-4b7a-b587-1d6cab5d45f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should receive validations for empty fields</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b70a66f1-8f56-4023-b65b-e906c08291bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should see self explainatory message after selecting consultation type while booking appointment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c36b2f8-d1b7-4aa2-9d32-0f423a1d0d01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0b25bc2-6174-4d3a-9260-89342ed739a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>623482c0-3de2-4122-a182-d54f629853c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should not able to continue with booking without selecting mandatory details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>276aec58-a42a-483b-8785-d7134b2b3129</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9373a25d-9377-4ca6-a129-1a632a79e13a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f4401b4-addc-44fa-b417-900b1c4cf452</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should not able to book appointment for unavailable time-slot</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2bed722-20fd-404f-a741-acf8c6d78c49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4356bb9f-ee9a-4382-896e-4060a0af3086</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb0d9ad7-2935-46e2-84da-6046322df816</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should not able to book appointment for date for past dates</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>339783a8-0bed-41eb-b5dc-8fc82109a9e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>920aa211-7b48-4415-85af-a76f0b67689d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0cfcc4b-2213-456d-bf65-db9eb897f40a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should able to book appointment for available time-slot</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13c24a33-ff1f-4184-8d61-041515df51c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b325cd2-eec7-4685-b653-eb4517a83ba3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>616011e9-fda2-47c3-847f-711a563c05a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should not able to book multiple appointments at same time slot</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb3f50b1-faf2-46b2-8ca8-72bf6718ea4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05e11b55-cc92-463e-bc1f-7a8908ae3a81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a1ab0df-ab12-4b02-9bd4-160104220ddf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should receive warning message if I tried to book appointment for same issue twice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c2087e3-2ab2-4c1a-a4ab-ecee9ccf0885</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>119f46e1-949b-41d4-b6ba-f1d0bb3794bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e1f6343-f52d-419d-8073-9c0bc458d218</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should able to book appointment with different time zone</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>988ea799-0fd7-44d1-9772-32dd1d13271b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c27d17aa-cbee-4b4f-9ed0-d5bd28473595</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3ddcbfa-68ff-4488-9547-476e1a7e075c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a memebr, I should see my booked appointments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0008b0c-c701-4f23-b0e1-25bdcf048ae5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afdad0fe-254a-4afc-8010-edc10559db1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f559311-8343-4cb0-b7e2-cddae114b5b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should able to cancel the scheduled appointment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edc4337c-0402-4fe6-9a38-bcd42f34accc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4b112ce-f10c-4c3d-8561-b732dbe1e891</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>912a6242-c191-4e4c-9d78-b65de4854c1d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should not able to re-schedule appointments with past dates</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>682f0d65-4520-4359-912c-6a641e8ba748</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should able to re-schedule upcoming appointments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>dd05c4f1-6cdc-49a3-b785-dc85673934f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should not see cancelled appointments under upcoming appointments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ed306293-1002-4172-baf0-1c972f5d4608</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Fertility Tracker/As a member I should able to edit cycle data on calendar</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29ec7753-d19b-4c49-8a01-ff5ed06e5288</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>032d6ff3-0720-4630-bbcf-356d5e590edb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e33276e9-7f50-497e-8686-d717ac6ae916</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Fertility Tracker/As a member, I should able to export data at fertility tracker</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02df0d83-7110-4c48-9462-235af67e14b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab4b9f8c-171e-4f82-870c-5853f688b65d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>881de09c-bc13-4013-9762-6cc27547e2a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Fertility Tracker/As a member, I should able to set reminders at fertility tracker</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87338a55-47f4-440d-a4ef-82ae3bfe4f15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d12dec0-0f5f-4a06-9bf7-d8d7f7267a32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf986a9e-f03c-460d-80f3-39c03f9ff441</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Fertility Tracker/As a member, I should able to write note for cycle data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4357daa0-b69e-4786-987d-570817051a7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8032411-b1ad-4095-8d7a-c3f7d4ac39ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f8e2ef0-1c9c-4704-b1ce-2cc2a4ddfb5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Fertility Tracker/As a member, I should receive validation message for mandatory fields while adding reminders</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d01209b9-1c53-4533-9c87-484dbd822bc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8565c990-f3e3-4d33-ab3a-891ea1b54b1c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e5f9470-3115-46e0-97d2-0706cca2a9d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Treatment/As a member, I should able to upload treatment documents</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a733844b-825f-4629-af96-71002a8af15a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Treatment/As a member, I should able to view already added treatments for review</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8e586ecb-db80-4566-a6e7-490c22204001</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Treatment/As a member, I should able to view letter for approved status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a1529116-8eb0-46cc-b4ed-e1831b5a384c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Search/As a member i should able to clear search</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c822200-9450-4aa6-a037-fd1d9b004d6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79d33c4f-faae-472b-b117-dc2694d09bd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15ce58d6-d50a-4c52-95b7-64e94da22a71</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f761d7dc-5014-42ab-a328-a28affb4a6f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Search/As a member I should able to search providers by city</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1397f5cf-e123-4deb-b2fc-fbcc29446045</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75974356-0f51-4540-bd24-c0b29d63af00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Search/As a member I should able to search providers by state</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a0286f8-ae6a-4e3e-8c73-03bf73c5c17e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11656d32-ce90-4416-9bf2-f4ab471f09f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Search/As a member I should able to search providers by zip code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>da85cafa-62ab-4024-ac01-bc361fe1f03c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Search/As a member, I should receive error message if no records found at search</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6f9d602-c447-4138-842f-e85ad700b6d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65e3b05a-da9d-487e-8cdb-979ec9cd1140</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
