<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Winfertility Tests - Android</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2b6cb1b8-3718-4e84-b8bf-62349049190e</testSuiteGuid>
   <testCaseLink>
      <guid>ec700fcd-081b-47b8-8549-84617f2e639d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should receive validations for mandatory fields at Signup screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>dde7ba75-b175-43f7-8ef8-09b5c368861f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should receive error message for invalid email format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed90fcc1-802f-4e8b-95ee-7a328c033289</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b810671-d7bd-472d-837f-7650a3d56518</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83278030-f4dc-4684-be5f-fe5b5242878f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c49ccae-7502-4649-8d99-18e664b77488</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd41204b-9de4-4560-907e-a404072516bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1df059e6-320c-4194-a005-8be5e7544021</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should receive error message for invalid password format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16721f66-436d-4785-8b0b-d7831ffcc215</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee5408ca-95b9-49fc-873b-e1b14ca57f85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b55c994c-a696-44d3-b783-07390be5b678</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3543a1a7-bd82-48f3-85e2-a68eb18c2743</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d0ac175-53af-4a7c-bb08-aaf12649eb91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35271510-1ad7-490a-a1d6-d3dae90b6434</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should receive error message for password mismatch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1fdc83d-21a6-41cc-9dcb-b1adcf69ae58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>533b4112-22d2-4aec-ace7-0b0336c2abfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec8622e8-0cba-488b-a229-0fd4f65c5645</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1427bd1-f36e-487f-a0fb-64d435b42b16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fb27864-0089-46f7-b208-9ae7adb8c780</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36098a8d-2b74-4e18-a816-1ebb6317ebb5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>671f7b0e-40b1-4854-8cf2-767d2814a722</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should able to view privacy policy and TnC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>dcebb45b-7376-4313-8430-855552283a6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a new user, I should able to fill up details at signup screen and proceed next</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74b9c9f8-fde3-4215-bab2-d8a7b323ba84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4e1eac2-738e-4220-a611-362beae9bd72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5c4d6ad-f7a7-4fb9-9a13-5446d6798263</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c601d1e0-e1ab-49a1-bfa5-7f4bc1c48870</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>287e6f82-cb0a-4785-ba76-ad2a54fc9535</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9600a385-c50f-4644-b231-79ff5b7ab24a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should not able to sign up using same email twice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c881c648-709f-4d3a-bb0c-4bcaef96f174</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f65ce06-658f-4842-a165-8803b11f33e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2790689-ccb3-4630-8be4-6ce2e8e1b50f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f086564-c48f-4166-82fc-b640c626b77f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64672c86-420c-4480-9a48-122c93018da3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b1ebb9e-10d9-48df-a84c-9f16e363ff55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should receive validations for mandatory fields at account setup screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20b69520-e0df-4316-a1dc-b40516bb1f35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e24d2058-9cd2-415a-b14d-a0905b795ed3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2dec550a-969c-42e4-a2cd-3b35a7737dc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should receive error message if my age is less than 16 years</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36e722da-cbcb-4c51-86c0-4fcaec0976dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52a56099-825d-436f-a454-acce92e82827</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>934d8c81-f5e6-4694-8284-a538f8d28a0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should able to fill DOB and Address at account setup screen and proceed to next</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a64b6822-6d26-402d-8a69-886c5e906971</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6330efa1-942f-408b-8890-6aeff5df5cf9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5afae562-9dee-4ad2-a509-c6e94947b2ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should able to enter Win access code and proceed next screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c072c777-498c-4e0c-ad19-09855058a0bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7cc60e4f-7f79-437e-a7ac-19727f71ceef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should able to select benefit provider and proceed to next screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>dc8f7e0c-fe75-48e5-8ace-bb148f1ee05c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should able to enter sponser company and proceed next screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9d4218e-8731-444f-bf31-a3a550b2cf5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8f89a9f-da88-4c2e-b57d-8078de1567d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should program eligibility verification message when I proceed next after entering sponsor company</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91fdc417-44c7-4294-a7c1-fd692eb5a911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf324462-6aa9-4af9-841e-d05b12cf7a4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>819e7298-83ed-404e-aa44-8ebd01a12679</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcc7a2c3-669a-49d7-b0dd-08c7dc5a9892</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5027271d-1b11-41ed-877f-7a438279783b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b774099c-93f8-4d61-96aa-2ab3c5cef2e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66dea418-0db6-4c84-a908-89babbce6c2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdae7544-0222-4d47-b3d4-1e74fb700449</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>837be50f-c78a-4c0d-8de0-144496d6ec44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c6a6935-820a-4075-a8ab-92c3f89621b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Signup/As a user, I should receive registration success message when I proceed next after entering Member ID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85e278f0-8b06-4d12-8b34-70c1927039ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db1096fb-352e-48cd-83f0-501636972a24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30377e30-00c7-4d48-8dd0-a7a40c97d303</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d6e6cd0-87d1-4929-bbcd-b0f994ac217b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a81cd296-06c9-4d0e-9904-87fe64feb958</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8170109-6310-4218-bd31-d99ab91a63a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ffc7083-3576-43e0-81a2-9e16f9f83370</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f125fa8a-82a1-4b36-9943-f095a7d7f959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3c07770-b5c7-42b0-91cc-71ca236b3610</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a67f1506-43f7-4475-8233-bbfbb40b3fc8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5938fdf-e45f-4f6e-8582-5bfc1e9f4b16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should able to login successfully with valid email and password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcf3fdb0-0b72-4324-8970-36afed531a18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d5bf77a-b203-4939-96fd-c89ec72fed92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>641d96dc-c9c4-4890-b65a-08191f34062a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should able to logout from application</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c88a5a3-5dc5-4a49-ae2a-c59baeae9948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b82907c-dd94-4eac-9ff0-5d2ba92adc06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f539cca-7514-4aaf-9f82-95bf0fe1f4e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should able to navigate to Forgot password screen using Forgot Password link and vice versa</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8e2a2a18-8197-454c-a216-d814eab64a55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should able to navigate to sign up screen using Create New Account link</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6288658c-207f-418d-b87e-36dab08defd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should receive error message for account locked after 3 unsuccessfull attempts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>760e25ba-e8b3-4ef6-b6a7-159089e494eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4fb42a4-1266-4806-9df5-c28b9226695d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7095f0d-2b71-406e-ad2c-62de3db7c490</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should receive error message for invalid email address</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44629149-cd8e-4425-9e98-8992eaa87982</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>327a9c44-330e-46a1-9366-712038f8cd45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>444ab84f-520a-4527-8f1e-fd72a1a55213</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should receive error message for invalid password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7db2c99f-33e5-4af8-8377-8e5627e96c1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20fad1de-f7f7-415d-92ea-48acebaf367a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b21f906a-b0d2-4b7a-b587-1d6cab5d45f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Sign In/As a user, I should receive validations for empty fields</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b70a66f1-8f56-4023-b65b-e906c08291bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should see self explainatory message after selecting consultation type while booking appointment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c36b2f8-d1b7-4aa2-9d32-0f423a1d0d01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0b25bc2-6174-4d3a-9260-89342ed739a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>623482c0-3de2-4122-a182-d54f629853c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should not able to continue with booking without selecting mandatory details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>276aec58-a42a-483b-8785-d7134b2b3129</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9373a25d-9377-4ca6-a129-1a632a79e13a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb0d9ad7-2935-46e2-84da-6046322df816</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should not able to book appointment for date for past dates</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>339783a8-0bed-41eb-b5dc-8fc82109a9e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>920aa211-7b48-4415-85af-a76f0b67689d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0cfcc4b-2213-456d-bf65-db9eb897f40a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should able to book appointment for available time-slot</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13c24a33-ff1f-4184-8d61-041515df51c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b325cd2-eec7-4685-b653-eb4517a83ba3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>616011e9-fda2-47c3-847f-711a563c05a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should not able to book multiple appointments at same time slot</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb3f50b1-faf2-46b2-8ca8-72bf6718ea4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05e11b55-cc92-463e-bc1f-7a8908ae3a81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a1ab0df-ab12-4b02-9bd4-160104220ddf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should receive warning message if I tried to book appointment for same issue twice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c2087e3-2ab2-4c1a-a4ab-ecee9ccf0885</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>119f46e1-949b-41d4-b6ba-f1d0bb3794bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e1f6343-f52d-419d-8073-9c0bc458d218</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should able to book appointment with different time zone</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>988ea799-0fd7-44d1-9772-32dd1d13271b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c27d17aa-cbee-4b4f-9ed0-d5bd28473595</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3ddcbfa-68ff-4488-9547-476e1a7e075c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a memebr, I should see my booked appointments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0008b0c-c701-4f23-b0e1-25bdcf048ae5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afdad0fe-254a-4afc-8010-edc10559db1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f559311-8343-4cb0-b7e2-cddae114b5b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should able to cancel the scheduled appointment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edc4337c-0402-4fe6-9a38-bcd42f34accc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4b112ce-f10c-4c3d-8561-b732dbe1e891</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>912a6242-c191-4e4c-9d78-b65de4854c1d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should not able to re-schedule appointments with past dates</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>682f0d65-4520-4359-912c-6a641e8ba748</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should able to re-schedule upcoming appointments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ff2df350-72f3-451f-874a-fd1f31af060a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Book Appointment/As a member, I should able to book Video consultation appointment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ed306293-1002-4172-baf0-1c972f5d4608</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Fertility Tracker/As a member I should able to edit cycle data on calendar</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29ec7753-d19b-4c49-8a01-ff5ed06e5288</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>032d6ff3-0720-4630-bbcf-356d5e590edb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e33276e9-7f50-497e-8686-d717ac6ae916</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Fertility Tracker/As a member, I should able to export data at fertility tracker</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02df0d83-7110-4c48-9462-235af67e14b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab4b9f8c-171e-4f82-870c-5853f688b65d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>881de09c-bc13-4013-9762-6cc27547e2a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Fertility Tracker/As a member, I should able to set reminders at fertility tracker</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87338a55-47f4-440d-a4ef-82ae3bfe4f15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d12dec0-0f5f-4a06-9bf7-d8d7f7267a32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf986a9e-f03c-460d-80f3-39c03f9ff441</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Fertility Tracker/As a member, I should able to write note for cycle data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4357daa0-b69e-4786-987d-570817051a7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8032411-b1ad-4095-8d7a-c3f7d4ac39ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f8e2ef0-1c9c-4704-b1ce-2cc2a4ddfb5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Fertility Tracker/As a member, I should receive validation message for mandatory fields while adding reminders</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d01209b9-1c53-4533-9c87-484dbd822bc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8565c990-f3e3-4d33-ab3a-891ea1b54b1c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1529116-8eb0-46cc-b4ed-e1831b5a384c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Search/As a member i should able to clear search</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c822200-9450-4aa6-a037-fd1d9b004d6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79d33c4f-faae-472b-b117-dc2694d09bd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15ce58d6-d50a-4c52-95b7-64e94da22a71</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f761d7dc-5014-42ab-a328-a28affb4a6f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Search/As a member I should able to search providers by city</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1397f5cf-e123-4deb-b2fc-fbcc29446045</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>090c64e6-b8ad-438f-a24c-786bd3864e89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56ce76ae-0e45-499a-bf01-0150dedb1438</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75974356-0f51-4540-bd24-c0b29d63af00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Search/As a member I should able to search providers by state</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a0286f8-ae6a-4e3e-8c73-03bf73c5c17e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f13f7ff9-999d-4287-8218-a709e3bc5872</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c791e5b-dc37-472e-9c3a-bb4a90e29439</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11656d32-ce90-4416-9bf2-f4ab471f09f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Search/As a member I should able to search providers by zip code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a30e7ffb-f3cd-440c-b795-574879d044f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aa0687e-9247-4b75-a539-5539b1add465</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da85cafa-62ab-4024-ac01-bc361fe1f03c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Search/As a member, I should receive error message if no records found at search</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6f9d602-c447-4138-842f-e85ad700b6d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65e3b05a-da9d-487e-8cdb-979ec9cd1140</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e5f9470-3115-46e0-97d2-0706cca2a9d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Treatment/As a member, I should able to upload treatment documents</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a733844b-825f-4629-af96-71002a8af15a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Treatment/As a member, I should able to view already added treatments for review</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8e586ecb-db80-4566-a6e7-490c22204001</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Treatment/As a member, I should able to view letter for approved status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b8ebfcc1-4136-4d58-a18b-e28aec576f3c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Benefit Accumulator/As a user, I should able to navigate back to Benefits screen from Benefit Accumulator screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a0b8247-61b6-4165-8e76-7248b4985731</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>053226c9-fa4e-461a-9c25-e5a25643385c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>579fcf8a-5fd8-4a53-8306-7b69c347a7e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Benefit Accumulator/As a user, I should able to navigate to Benefit Accumulator screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c016e85-8e51-478b-91b4-955942c20198</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb9dae87-025a-4885-8f8c-ab93a367b913</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59ecfd58-34a6-4280-bfdd-340556d3e62f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Benefit Accumulator/As a user, I should able to navigate to Request Reimbursement screen from Benefit Accumulator</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60e1bb4e-a651-48bd-9a8e-3ba17238010b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84a77c1d-dfac-443b-991a-680889d620e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>895f6533-c040-465e-930b-94e662539911</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Benefit Accumulator/As a user, I should able to share Benefits Accumulator report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50453fa1-6849-451d-9b2b-84c5c0b119ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>694830df-c999-44c4-adb8-143ff0968db3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>863f1bfd-5c6f-42a8-9044-d3dee6d7b93d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/My Documents/As a user I shold able to view any PDF document listed at My Dcouments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4013ff5c-254b-4d16-aaa8-49a51dc51e46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dad110d-9a56-4694-82da-8ae8bf0f1f0b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d432d82-5fee-4fb8-b8fd-bb9f7cc782ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/My Documents/As a user, I should able to download the document from My Documents</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f518270-f99b-4d07-85fc-d69d9dcaa872</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eae29d2-61fd-4301-a46f-7543cdff4ea1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a10b3412-b92d-4320-b0ca-15242e4442fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/My Documents/As a user, I should able to navigate back to Benefits screen from My Documents</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d24a12e8-16ed-49ab-8a2b-c4e0fd8ff491</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c635c53a-da43-4013-84c8-fb3da1fb2e5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18d78432-5c29-49b2-b311-62eb41dfafc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/My Documents/As a user, I should able to navigate to My Documents screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f44921a-49d3-4311-b54b-767cebf90803</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf2c4e09-745b-44d9-bb95-f714a8a99798</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>545d65fe-fb4b-4acd-bd27-65da27b39817</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/My Documents/As a user, I should able to print the document from My Documents</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5065a5f-9f22-40b9-a086-d55e873be11d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8988519-7cac-48c2-8494-cc058920fb1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a6263f1-1ce8-408f-bae9-66653f811841</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/ParientID/As a user, I should able to navigate back from Patient ID screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9746d1-f68c-4a06-aff3-61e0cba7f029</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c494f69b-fff5-4e7d-8f26-c3c54d8f7c03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>958711e9-4f79-4d8d-9b08-6b01892bef61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/ParientID/As a user, I should able to view Patient ID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>becfaaf5-40e6-4bab-91f6-bcffb9893620</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8dfaf5b-0a98-4232-8e96-3da633447a7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1039e5db-e2d1-48c2-a977-1b958a2ccb5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/PHI form/As a user, I should able to navigate back to Benefits screen from PHI form screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a4ad06a-fc94-4047-8418-93472579bede</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ba41fcf-8a61-42ce-a0c7-5cd357621a4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>395434f1-ad01-45a0-a93f-3bcb26fa044a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/PHI form/As a user, I should able to navigate to the PHI form screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40c7b2fe-bf2a-4e30-84b9-0c91cb7e6b59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce3de8e4-3d46-4bc7-a0a7-b3a1c0ee433c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dfc07e1c-c523-4deb-b510-5d1a698d241b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/PHI form/As a user, I should able to enter details at PHI screen and submit the form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c3df51a-c53e-4fbb-b853-bcf96d03cf4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>369dc9b1-8a47-4a57-90fe-445532ba8a95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69ee60e7-37cd-4867-afc4-c2f66e1f4560</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Request Reimbursement/As a user, I should able to navigate back from Request Reimbursement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d882a60c-279e-4cc2-977c-75a7d52a25d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5f7e42d-d596-419f-95be-5c4285264daf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bbeb2663-1a89-4440-bfad-b307bbee8966</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Request Reimbursement/As a user, I should able to submit Request Reimbursement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e788e06-80ed-4811-8814-429912c0a7f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a900fbb3-c144-4bd4-9d5b-8ee620b1ce95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>721764ba-441d-4e4d-9d45-082b94b4a52b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Rx Authorization/As a member i should able to change pharmacy while processing Rx</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>428e13e7-edcb-47da-9797-f687736ca077</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbab8d12-acfb-4a42-8e29-e35c0e3f0af0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05053b42-d528-4f61-87e8-8225c6a01df8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Rx Authorization/As a member, I should able to set appointment with nurse from Rx screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd26dace-fcb7-432b-8939-886c3b013996</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a0d3860-cfb2-4eba-b6c3-21ca98f645f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47cfc2f8-2fc0-4295-8ad1-1f9173238fa9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8232945d-c147-47de-ac07-d99408891311</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Rx Authorization/As a user, I should able to navigate back to the rx authorization screen from Rx review screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f42335e1-9e86-4d74-9670-253e0e9e7d2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b361cd69-daf4-40fb-adf7-dc4d95b9ce35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0649260-ab8f-4cc3-b273-6dc68ac43ea0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Rx Authorization/As a user, I should able to navigate to Rx Authorization screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79c2c89c-1c7c-4b3b-a369-db4f11fd98b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0a27765-341e-42d4-a1af-a6da69af2eeb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7880861a-9e6b-4dbe-8024-598fb802cedb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Rx Authorization/As a user, I should able to process the Rx</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d4bd9a-3579-452e-ab49-f0c7146b5b31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9bf2697-1f1f-4aa3-ab56-8c6e8b9730c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb8b920d-672b-4ba9-b681-a7b79c3972f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6cea3db7-18ee-4cda-87f1-c9a236d1e999</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Rx Authorization/As a user, I should able to view existing Rx</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>454531ca-5709-41f4-8a4d-be4b0e1b38ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a48da92-d409-45ce-bbe2-69d7360c0075</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50aeb323-92cc-4db2-b6a6-dd751fa0f002</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Rx Authorization/As a user, I should receive error validation for empty fields while processing RX</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e74bcc1-22fc-4044-ad11-e05d88fd657b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>614c1201-3987-4ef5-9bc3-648fa6ebf575</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce0b1e16-d474-476c-baa5-f9df3ea5179c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Treatment Cost Etimator/As a user, I should able to change provider at Treatment cost estimater screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70f5d52a-c523-49c2-b5ff-7a304d2e7ece</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3080ef8a-610a-46e1-a9ca-e03e3ad6cc8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d82f974-c936-4db0-bdcf-111d913e055d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b60875d-db91-4025-b272-ded5ef5221b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Treatment Cost Etimator/As a user, I should able to navigate back to Benefits screen from Cost Estimator screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56e3c476-baf4-4357-96df-b0e4fbff6165</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ef7c11a-7e2f-43d9-9fb1-617fc114a5a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bddf5e0d-6570-47d6-b7de-51547f28c6b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Treatment Cost Etimator/As a user, I should able to navigate to Treatment Cost Estimator screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f8892c9-674d-4a6c-813b-6f6fd0cbc6d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1020301-22db-401c-9a2d-faf2d6ed8881</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0313302-bb9e-4ab0-a840-cade833dc7d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Treatment Cost Etimator/Verify that valid cost is being estimated for Egg Freezing treatment package</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ca5794a-3328-41fd-894a-fb5cb22723d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d19913c6-0b9c-429b-9775-22bfe249f118</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c080bcc-6dc0-46eb-9635-4a33e3b598cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c000a39d-e95a-4c4f-a3ab-59ee731b4619</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Treatment Cost Etimator/Verify that valid cost is being estimated for FET treatment package</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17eeeb02-2c16-4596-a94b-0d90bceeb6fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a05b6df5-9f9c-43e4-af4b-11a8b9024b11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62cdbaeb-f372-4132-a132-f504e45879ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc9decfb-bdea-4cf5-9074-d21bf87a20d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Treatment Cost Etimator/Verify that valid cost is being estimated for IUI treatment package</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04f963db-8d4b-495f-ad01-f50f6efd8735</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6252ca3e-ae6d-457b-85b4-f660a558e6e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc60149e-0dd4-44ad-bb8c-71a954468eb5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e9bb499-c97b-47d4-8d47-47e766a064d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Benefits/Treatment Cost Etimator/Verify that valid cost is being estimated for IVF treatment package</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a54fefd-a621-4d9b-a8f0-a03e3ae45b0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3aa4f46a-a9c5-4256-b65c-ef50a9fc9a49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6652c2d8-027f-4666-90d2-8f2832f19c10</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a89f06d7-b8cf-4db8-a924-2d0c1f15ab44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Support/Preconception/As a member, I should able navigate to Preconception WIN Resources screen to explore articles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f6c99d20-c433-46a0-8214-64cd5df021aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Support/Preconception/As a member, I should able to navigate to Ava fertility application to order Ovulation tracking bracelet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b6cf1e68-9948-4773-84c0-2ad3bd9e2fb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Support/Preconception/As a member, I should able to navigate to Legacy application to order Testing Kit from Win app</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>bcd92043-2e21-45a7-9b9b-0d74cbe8303e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Support/Preconception/As a member, I should able to view any article from Preconception WIN Resources screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>82491508-4776-454a-8b4e-4b7afe640e9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Support/Win For Him/As a member, I should able navigate to WIN Resources screen to explore articles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3dd116d9-4f91-4e3d-bab7-69b3d3261ef3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Support/Win For Him/As a member, I should able to navigate to Legacy application to order Testing Kit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>75ab8662-8ce4-436a-bec0-50f80c5ba07e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Support/Win For Him/As a member, I should able to view any article from WIN Resources screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>07e2369e-5c96-4a18-ad4d-ecefb546a4ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Reset Password/As a user, I should able to navigate back from Reset Password screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c291358b-4bf4-4821-8601-ad41d30a046b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Reset Password/As a user, I should able to navigate to Reset Password screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a0712140-400b-4d13-9224-818f3c1cd28c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Reset Password/As a user, I should able to reset Password successfully</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fb83d8d-a64e-4aee-aaef-9965463a2948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e60499-f8b0-458e-b0a7-52241c73fad5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76f7d1ba-5afd-4aef-8e8f-6d3934099834</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Reset Password/As a user, I should receive error message when new password and confirm password doesnt match</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe8e5063-9c8c-459b-880f-73a4bec6cfc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abd210d6-01fc-46f8-863b-3551f6217448</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>112cfc05-226e-43ff-99c1-9829836f42c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8a8bea3-3702-4ec5-9386-608a4b6fa225</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Reset Password/As a user, I should receive error messages for password format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d1650de-0508-46c1-a18d-7bdc36c969b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf231508-c47c-4c85-be8e-801fa2cb7b88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f037e0d-061c-4268-a436-e7591c2ea02c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Reset Password/As a user, I should receive validation messages for empty fields at reset password screen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1101b8ec-491a-4838-900a-d39b94bee1ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6987444e-9288-4c99-8420-dbd2657800e7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
